version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cs2_simulator
      POSTGRES_USER: cs2_user
      POSTGRES_PASSWORD: cs2_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/cs2_simulator
      SPRING_DATASOURCE_USERNAME: cs2_user
      SPRING_DATASOURCE_PASSWORD: cs2_password
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: